### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by huming0618** [huming0618/treeit#7]
- [ ] follow the selection
   - [ ] drop & drag
   - [ ] follow the selection 
- [ ] make the note
  - [ ] make the note 
  - [ ] make the tree
